
server:
  port: 8081

spring:
  application:
    name: registration-service

  datasource:
    url: jdbc:mysql://localhost:3306/registration_db
    username: root
    password: Mysql@234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
