
server:
  port: 8082

spring:
  application:
    name: authentication_service
  datasource:
    url: jdbc:mysql://localhost:3306/authentication_db
    username: root
    password: Mysql@234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

